### ISSUE TITLE
Invalid frequency undefined - Error when instantiating client

### ISSUE THREAD

**Issue by ozzyonfire** [transitive-bullshit/openai-realtime-api#4]
I'm getting this error when instantiating the client. 

Coming from the assert in the RealtimeConversation constructor. 

Even though the defaultFrequency looks like it should be getting applied, it doesn't when being called from the RealtimeClient constructor. 

I can submit a PR. 

Also great work on this repo, I was just about to dive in and convert it to typescript myself when I found this!

**Comment by transitive-bullshit** [comment]
Should be fixed in https://github.com/transitive-bullshit/openai-realtime-api/releases/tag/v1.0.6

Thanks @ozzyonfire 🙏
