### ISSUE TITLE
Invalid URL Error with Relay Server

### ISSUE THREAD

**Issue by arjunlall** [transitive-bullshit/openai-realtime-api#9]
When trying to connect to the relay server I was get a TypeError: Invalid URL at this line every time the client connects.

I made a PR to fix this here: https://github.com/transitive-bullshit/openai-realtime-api/pull/8

**Comment by transitive-bullshit** [comment]
Thanks! Will release a new version shortly.

**Comment by transitive-bullshit** [comment]
https://github.com/transitive-bullshit/openai-realtime-api/releases/tag/v1.0.7
